# Generated by Django 3.1.7 on 2021-02-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chirp',
            fields=[
                ('text', models.CharField(max_length=140)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
