# Generated by Django 3.1.7 on 2021-02-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirp',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
